org: nxdanh
app: my-aws-node-express-api-app
service: my-aws-node-express-api-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - events:PutEvents
          Resource: <ARN of your EventBridge>
plugins:
  - serverless-offline


functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

  consumer1:
    handler: consumer.successHandler
    events:
      - eventBridge:
          pattern:
            source:
              - custom.myATMapp
            detail-type:
              - UserSignup
            detail:
              state:
                - success

  consumer2:
    handler: consumer.failHandler
    events:
      - eventBridge:
          pattern:
            source:
              - custom.myATMapp
            detail-type:
              - UserSignup
            detail:
              state:
                - fail